import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import Layout from "~/components/Layout";
import { ServicesPanels } from "~/components/ServicesPanels";
import { Shoutout } from "~/components/Shoutout";
import Socials from "~/components/Socials";

const Home: NextPage = () => {
  const services = [
    {
      text: "Weddings",
      img: "https://images.unsplash.com/photo-1637616919953-5943e10bd4bf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
      path: "/services/weddings",
    },
    {
      text: "Parties",
      img: "https://images.unsplash.com/photo-1640506054499-2b040ca19023?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=531&q=80",
      path: "/services/parties",
    },
    {
      text: "Arrangements",
      img: "https://images.unsplash.com/photo-1608153917926-c467b4e23b6f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
      path: "/services/arrangements",
    },
  ];

  const photos = [
    "https://i.ibb.co/8Y9yVwq/f.jpg",
    "https://i.ibb.co/7VVYdmT/b.jpg",
    "https://i.ibb.co/fSPrjqx/c.jpg",
    "https://i.ibb.co/qp7N6CZ/d.jpg",
    "https://i.ibb.co/RNHPjh7/e.jpg",
    // "https://i.ibb.co/8x07XRC/g.jpg",
    "https://i.ibb.co/Hn0zx5H/h.jpg",
    // "https://i.ibb.co/4pps6DC/i.jpg",
    // "https://i.ibb.co/L01NSXy/j.jpg",
    // "https://i.ibb.co/NrBtctK/k.jpg",
    // "https://i.ibb.co/8XBc8fB/l.jpg",
    // "https://i.ibb.co/NC3CG8n/m.jpg",
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <Layout>
          <div className="relative">
            <img src="/splash.jpg" className="opacity-80" />
          </div>
          <div className="mx-auto my-20 w-8/12 border border-l-0 border-r-0 border-pinky ">
            <p className="sm:text:xl p-10 text-center md:text-4xl">
              DEDICATED TO MAKING YOUR EVENT BEAUTIFUL AND UNFORGETTABLE
            </p>
          </div>
          <ServicesPanels title="Services" images={services} />
          <Shoutout
            title="Lets make your dream a reality"
            buttonText="contact me"
            path="/contact"
          />
          <Socials images={photos} />
        </Layout>
      </main>
    </>
  );
};

export default Home;
